project:
  type: website

website:
  title: "Map Templates"
  navbar:
    left:
      - href: index.qmd
        text: Site Map
      - locator-map.qmd
      - population-map.qmd
      - watershed-map.qmd
      - lulc-map.qmd

format:
  html:
    highlight-style: github
    theme: cosmo
    css: styles.css
    code-fold: false
    code-copy: true
    code-overflow: scroll
    toc: true
    grid:
      sidebar-width: 300px
      body-width: 900px
      margin-width: 300px
      gutter-width: 1.5rem

editor: visual

